### ISSUE TITLE
Check on 0th index of array. Not correct

### ISSUE THREAD

**Issue by vpulagarwal** [xebialabs-community/xlr-apigee-test-plugin#3]
https://github.com/xebialabs-community/xlr-apigee-test-plugin/blob/ab39937edc5bcfde784a53073bf3387053d21e82/src/main/resources/apigee/ApigeeClient.py#L61

Apigee returns an array of deployed revisions. In case of multiple revision deployed to an env, the latest deployed revision is at the last index of an array. So the check should not be for the first index element. Do it based on the length of the array.

**Comment by ltutar** [comment]
See https://github.com/xebialabs-community/xlr-apigee-test-plugin/releases/tag/v1.1.0
